apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-service
  labels:
    app: config-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-service
  template:
    metadata:
      labels:
        app: config-service
    spec:
      imagePullSecrets: 
        - name: dockerconfigjson-github-com
      containers:
        - name: config-service
          image: ghcr.io/codingkiddo/config-service:0.0.7-SNAPSHOT
          imagePullPolicy: Always
          ports:
            - containerPort: 8888
          env:
            - name: BPL_JVM_THREAD_COUNT
              value: "50"
