apiVersion: v1
kind: Service
metadata:
  name: config-service
  labels: 
    app: config-service
spec:
  type: ClusterIP
  selector: 
    app: config-service
  ports:
    - targetPort: 8888
      port: 80
      protocol: TCP